add two more agents & controllers and simple check for guid
NikitaKop/Practice2021 pull request #1
Opened 2021-06-13 13:27 UTC by NikitaKop

2021-06-13 21:12 UTC, chesdenis requested changes
Please apply changes to your code based on my suggestions

2021-06-13 21:12 UTC, chesdenis commented on Controllers/TextSynthesizerController.cs
> +            else this.HttpContext.Response.Cookies.Append("JobId", Guid.NewGuid().ToString("N"));
Let's refactor it to static extension to CookiesCollection like Guid GetOrCreateCookie(this CookieCollection cookieCollection)

2021-06-13 21:12 UTC, chesdenis commented on Controllers/WeatherForecastController.cs
> +            else this.HttpContext.Response.Cookies.Append("JobId", Guid.NewGuid().ToString("N"));
same as above. if you are starting to write same code - it is required to consider reusability

2021-06-13 21:12 UTC, chesdenis commented on Controllers/WebCameraController.cs
> +            else this.HttpContext.Response.Cookies.Append("JobId", Guid.NewGuid().ToString("N"));
Same as above

2021-06-13 21:12 UTC, chesdenis commented on TextSynthesizer.cs
> +    public class TextSynthesizer
Where is the string Text {get; set;} - How we can pass text to generate voice?

2021-06-13 21:12 UTC, chesdenis commented on WeatherForecast.cs
> +        public string Source { get; set; }
You don't need to specify direct source, because it will be identified based on vendor's/agents availability. But if you want include Source for reference (i.e. just to understand which vendor was used to get weather - it is acceptable)

2021-06-13 21:12 UTC, chesdenis commented on WebCamera.cs
> +    public class WebCamera
Is it input data? or output? I would like to say - that class name is incorrect. For example if this class is using for Request, it must contain Request postfix => WebCameraRequest. Same rule for responses => WebCameraResponse even if it will contain just byte[] property.

2021-06-15 11:33 UTC, NikitaKop commented on WeatherForecast.cs
> +        public string Source { get; set; }
I think that might be quite useful for some users so let's include it in the output

2021-06-15 12:04 UTC, chesdenis commented on Extensions/HttpContextExtensions.cs
> +                return Guid.Empty;
Guid.Empty?

2021-06-15 12:06 UTC, chesdenis requested changes

2021-06-15 12:06 UTC, chesdenis commented on Extensions/HttpContextExtensions.cs
> +        public static Guid AssignJobId(this HttpContext httpContext)
Missing args Action<Guid> OnCheckExistedJobStatus, Action<Guid> OnCreateNewJob

2021-06-15 12:18 UTC, NikitaKop commented on Extensions/HttpContextExtensions.cs
> +        public static Guid AssignJobId(this HttpContext httpContext)
I decided that we can left it without actions and just return Guid.Empty if the JobId was just created. If we received the guid from the client, we return it and do smth with it, otherwise we append new Guid in the cookie and that's all, isn't it? Or we are going to do smth more with just created guid in the controllers?

2021-06-15 22:01 UTC, chesdenis approved these changes

2021-06-17 13:18 UTC, merged